tasks:
  -init: npm i -g @angular/cli 
  command: > ng serve --host 0.0.0.0 --disable-host-check && gp await-port 4200 && gp preview $(gp url 4200)
ports:
  - port: 4200
    onOpen: open-browser      